name: Epidemy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: 6
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        cp student_map.example.json student_map.json
        npm ci
    - name: running tests
      run: |
        npm test
        cp student_map.example.json student_map.json
      env:
        CI: true
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
