name: Epidemy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
    - run: |
        cp student-map.example.json student_map.json
        npm ci
    - name: running tests
    - run: |
        npm test
        cp student-map.example.json student_map.json
